-- 해당 계정의 모든 트리거 삭제
BEGIN
FOR C IN (SELECT * FROM USER_TRIGGERS) LOOP
  EXECUTE IMMEDIATE 'DROP TRIGGER '||C.TRIGGER_NAME;
END LOOP;
END;
/
--해당 계정의 모든테이블 및 제약조건 삭제
BEGIN
    FOR C IN (SELECT * FROM USER_TABLES) LOOP
    EXECUTE IMMEDIATE ('DROP TABLE "'||C.TABLE_NAME||'" CASCADE CONSTRAINTS');
    END LOOP;
END;
/
--해당 계정의 모든 시퀀스 삭제
BEGIN
FOR C IN (SELECT * FROM USER_SEQUENCES) LOOP
  EXECUTE IMMEDIATE 'DROP SEQUENCE '||C.SEQUENCE_NAME;
END LOOP;
END;
/
--해당 계정의 모든 뷰 삭제
BEGIN
FOR C IN (SELECT * FROM USER_VIEWS) LOOP
  EXECUTE IMMEDIATE 'DROP VIEW '||C.VIEW_NAME;
END LOOP;
END;
/

CREATE TABLE "MZYM_MEMBER" (
	"USER_NO"	NUMBER		NOT NULL,
	"USER_ID"	VARCHAR2(20)		NOT NULL,
	"USER_PWD"	VARCHAR2(30)		NOT NULL,
	"USER_NAME"	VARCHAR2(50)		NOT NULL,
	"PHONE"	VARCHAR2(13)		NOT NULL,
	"RRN"	VARCHAR2(20)		NOT NULL,
	"EMAIL"	VARCHAR2(100)		NOT NULL,
	"ADDRESS"	VARCHAR2(100)		NOT NULL,
	"ENROLL_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"TR_CAREER"	VARCHAR2(2000)		NULL,
	"CERTIFICATE"	VARCHAR2(2000)		NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"ASSIGN_TR"	NUMBER		NULL,
	"IMAGE_URL"	VARCHAR2(500)		NULL
);

COMMENT ON COLUMN "MZYM_MEMBER"."TR_CAREER" IS '트레이너전용';

COMMENT ON COLUMN "MZYM_MEMBER"."CERTIFICATE" IS '트레이너전용';

COMMENT ON COLUMN "MZYM_MEMBER"."STATUS" IS '회원상태('Y'|'N'|'T'|'A'))';

COMMENT ON COLUMN "MZYM_MEMBER"."ASSIGN_TR" IS '담당트레이너';

COMMENT ON COLUMN "MZYM_MEMBER"."IMAGE_URL" IS 'resources/xxxx/xxxx.jpg';

CREATE TABLE "MZYM_NOTICE" (
	"NOTICE_NO"	NUMBER		NOT NULL,
	"NOTICE_WRITER"	NUMBER		NOT NULL,
	"NOTICE_TITLE"	VARCHAR2(200)		NOT NULL,
	"NOTICE_CONTENT"	VARCHAR2(2000)		NOT NULL,
	"REGIST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"EDIT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"START_DATE"	VARCHAR2(100)		NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "MZYM_NOTICE"."STATUS" IS '글상태('Y'|'N')';

CREATE TABLE "BOARD_CATEGORY" (
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"CATEGORY_NAME"	VARCHAR2(30)		NOT NULL
);

COMMENT ON COLUMN "BOARD_CATEGORY"."CATEGORY_NO" IS '카테고리 번호';

COMMENT ON COLUMN "BOARD_CATEGORY"."CATEGORY_NAME" IS '카테고리 명';

CREATE TABLE "ATTACHMENT" (
	"FILE_NO"	NUMBER		NOT NULL,
	"ATT_NO"	NUMBER		NULL,
	"ATT_CATEGORY"	CHAR(1)		NULL,
	"ORIGIN_NAME"	VARCHAR2(100)		NOT NULL,
	"CHANGE_NAME"	VARCHAR2(300)		NOT NULL,
	"FILE_PATH"	VARCHAR2(500)		NULL,
	"UPLORD_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"FILE_LEVEL"	NUMBER		NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NULL
);

COMMENT ON COLUMN "ATTACHMENT"."FILE_NO" IS '고유번호';

COMMENT ON COLUMN "ATTACHMENT"."ATT_NO" IS '10';

COMMENT ON COLUMN "ATTACHMENT"."ATT_CATEGORY" IS '유형('N' | 'B' | 'P')';

COMMENT ON COLUMN "ATTACHMENT"."ORIGIN_NAME" IS '회원 업로드한 파일명';

COMMENT ON COLUMN "ATTACHMENT"."CHANGE_NAME" IS '서버에 저장될 파일명';

COMMENT ON COLUMN "ATTACHMENT"."STATUS" IS '파일상태('Y'|'N')';

CREATE TABLE "MZYM_ADVICE" (
	"ADVICE_NO"	NUMVER		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"ADVICE_TR"	NUMBER		NULL,
	"ADVICE_USER"	VARCHAR2(100)		NOT NULL,
	"PHONE_NO"	NUMBER		NOT NULL,
	"ADVICE_DATE"	VARCHAR2(100)		NOT NULL,
	"ADVICE_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"REGIST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"ADVICE_REPEAT"	VARCHAR2(4000)		NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "MZYM_ADVICE"."ADVICE_TR" IS '트레이너';

COMMENT ON COLUMN "MZYM_ADVICE"."STATUS" IS '글상태('Y'|'N')';

CREATE TABLE "REPORT_CATEGORY" (
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"CATEGORY_NAME"	VARCHAR2(10)		NOT NULL
);

COMMENT ON COLUMN "REPORT_CATEGORY"."CATEGORY_NO" IS '카테고리 번호';

COMMENT ON COLUMN "REPORT_CATEGORY"."CATEGORY_NAME" IS '카테고리 명';

CREATE TABLE "MZYM_BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"BOARD_WRITER"	NUMBER		NOT NULL,
	"BORAD_TYPE"	NUMBER		NOT NULL,
	"BOARD_TITLE"	VARCHAR2(200)		NOT NULL,
	"BOARD_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"REGIST_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NULL,
	"REVIEW_RATE"	NUMBER		NULL,
	"COUNT"	NUMBER	DEFAULT 0	NOT NULL
);

COMMENT ON COLUMN "MZYM_BOARD"."BOARD_NO" IS '글번호';

COMMENT ON COLUMN "MZYM_BOARD"."BORAD_TYPE" IS '게시판유형';

COMMENT ON COLUMN "MZYM_BOARD"."STATUS" IS ''Y'|'N'';

COMMENT ON COLUMN "MZYM_BOARD"."REVIEW_RATE" IS '리뷰 평점';

CREATE TABLE "MZYM_SERVICE" (
	"SERVICE_NO"	NUMVER		NOT NULL,
	"SERVICE_USER"	NUMBER		NOT NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"SERVICE_TITLE"	VARCHAR2(200)		NOT NULL,
	"SERVICE_CONTENT"	VARCHAR2(4000)		NOT NULL,
	"REGIST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"EDIT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"SERVICE_TR"	VARCHAR2(100)		NULL,
	"SERVICE_REPEAT"	VARCHAR2(4000)		NULL,
	"REPEAT_DATE"	VARCHAR2(100)		NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "MZYM_SERVICE"."SERVICE_TR" IS '트레이너';

COMMENT ON COLUMN "MZYM_SERVICE"."STATUS" IS '글상태('Y'|'N')';

CREATE TABLE "BOARD_COMMENT" (
	"COMMENT_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"COMMENT_WRITER"	NUMBER		NOT NULL,
	"USER_NAME"	VARCHAR2(50)		NOT NULL,
	"COMMENT_DATE"	VARCHAR2(100)	DEFAULT SYSDATE	NOT NULL,
	"COMMETN_CONTENT"	VARCHAR2(1500)		NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "BOARD_COMMENT"."COMMENT_NO" IS '댓글번호';

COMMENT ON COLUMN "BOARD_COMMENT"."BOARD_NO" IS '글번호';

COMMENT ON COLUMN "BOARD_COMMENT"."COMMENT_WRITER" IS '회원번호';

COMMENT ON COLUMN "BOARD_COMMENT"."USER_NAME" IS '작성자';

COMMENT ON COLUMN "BOARD_COMMENT"."COMMENT_DATE" IS '작성일';

COMMENT ON COLUMN "BOARD_COMMENT"."COMMETN_CONTENT" IS '댓글내용';

COMMENT ON COLUMN "BOARD_COMMENT"."STATUS" IS '댓글상태('Y'|'N')';

CREATE TABLE "PRODUCT" (
	"PRODUCT_NO"	NUMBER		NOT NULL,
	"RPODUCT_NAME"	VARCHAR2(1000)		NOT NULL,
	"PRODUCT_CONTENT"	VARCHAR2(1500)		NOT NULL,
	"PRODUCT_PRICE"	NUMBER		NOT NULL,
	"REGIST_DATE"	DATE	DEFAULT SYSDATE	NULL
);

COMMENT ON COLUMN "PRODUCT"."PRODUCT_NO" IS '상품번호';

COMMENT ON COLUMN "PRODUCT"."RPODUCT_NAME" IS '상품명';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_CONTENT" IS '상품내용';

COMMENT ON COLUMN "PRODUCT"."PRODUCT_PRICE" IS '상품가격';

COMMENT ON COLUMN "PRODUCT"."REGIST_DATE" IS '상품등록일';

CREATE TABLE "MZYM_VIDEO" (
	"VIDEO_NO"	NUMBER		NOT NULL,
	"VIDEO_TITLE"	VARCHAR2(200)		NOT NULL,
	"LINK"	VARCHAR2(200)		NOT NULL,
	"STATUS"	CHAR(1)		NOT NULL,
	"VIDEO_LEVEL"	NUMBER		NOT NULL
);

CREATE TABLE "REPORT" (
	"REPORT_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NULL,
	"COMMENT_NO"	NUMBER		NULL,
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"REPORT_USER"	NUMBER		NOT NULL,
	"REPORT_DATE"	VARCHAR2(100)	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL
);

COMMENT ON COLUMN "REPORT"."REPORT_NO" IS '신고번호';

COMMENT ON COLUMN "REPORT"."BOARD_NO" IS '글번호';

COMMENT ON COLUMN "REPORT"."COMMENT_NO" IS '댓글번호';

COMMENT ON COLUMN "REPORT"."CATEGORY_NO" IS '카테고리 번호';

COMMENT ON COLUMN "REPORT"."REPORT_DATE" IS '신고날짜';

COMMENT ON COLUMN "REPORT"."STATUS" IS '신고여부('Y'|'N')';

CREATE TABLE "MZYM_CALENDAR" (
	"CAL_NO"	NUMBER		NOT NULL,
	"USER_NO"	NUMBER		NOT NULL,
	"CAL_TR"	VARCHAR2(100)		NOT NULL,
	"START_DATE"	VARCHAR2(100)		NOT NULL,
	"END_DATE"	VARCHAR2(100)		NOT NULL,
	"CAL_TITLE"	VARCHAR2(200)		NOT NULL,
	"CAL_CONTENT"	VARCHAR2(4000)	DEFAULT '내용이 없습니다.'	NOT NULL,
	"CAL_COLOR"	VARCHAR2(100)		NULL,
	"REGIST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"MODIFY_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	CHAR(1)	DEFAULT 'Y'	NOT NULL,
	"Field"	VARCHAR(255)		NULL
);

COMMENT ON COLUMN "MZYM_CALENDAR"."START_DATE" IS '시작날짜';

COMMENT ON COLUMN "MZYM_CALENDAR"."END_DATE" IS '끝날짜';

COMMENT ON COLUMN "MZYM_CALENDAR"."STATUS" IS '상태('Y'|'N')';

CREATE TABLE "PAYMENT" (
	"PAYMENT_NO"	NUMBER		NOT NULL,
	"PRODUCT_NO"	NUMBER		NOT NULL,
	"PAYMENT_USER"	NUMBER		NOT NULL,
	"PAYMENT_PRICE"	NUMBER		NOT NULL,
	"PAYMENT_DATE"	DATE	DEFAULT SYSDATE	NOT NULL,
	"STATUS"	CHAR(1)		NOT NULL
);

COMMENT ON COLUMN "PAYMENT"."PAYMENT_NO" IS '구매번호';

COMMENT ON COLUMN "PAYMENT"."PRODUCT_NO" IS '상품번호';

COMMENT ON COLUMN "PAYMENT"."STATUS" IS '사이트(S)/워크인(W)';

CREATE TABLE "FOOD" (
	"FOOD_NO"	NUMBER		NOT NULL,
	"FOOD_USER"	NUMBER		NOT NULL,
	"FOOD_DATE"	VARCHAR2(100)		NOT NULL,
	"FOOD_CATEGORY"	CHAR(1)		NOT NULL,
	"FOOD_NAME"	VARCHAR2(100)		NOT NULL,
	"FOOD_CAL"	NUMBER		NOT NULL,
	"REGIST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

COMMENT ON COLUMN "FOOD"."FOOD_CATEGORY" IS '아침점심저녁간식';

CREATE TABLE "INBODY" (
	"USER_NO"	NUMBER		NOT NULL,
	"BODY_HEIGHT"	NUMBER		NULL,
	"BODY_WEIGHT"	NUMBER		NULL,
	"BODY_METABOLISM"	NUMBER		NULL,
	"BODY_FAT"	NUMBER		NULL,
	"REGIST_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);

CREATE TABLE "SERVICE_CATEGORY" (
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"CATEGORY_NAME"	VARCHAR2(50)		NOT NULL
);

CREATE TABLE "ADVICE_CATEGORY" (
	"CATEGORY_NO"	NUMBER		NOT NULL,
	"CATEGORY_NAME"	VARCHAR2(50)		NOT NULL
);

ALTER TABLE "MZYM_MEMBER" ADD CONSTRAINT "PK_MZYM_MEMBER" PRIMARY KEY (
	"USER_NO"
);

ALTER TABLE "MZYM_NOTICE" ADD CONSTRAINT "PK_MZYM_NOTICE" PRIMARY KEY (
	"NOTICE_NO"
);

ALTER TABLE "BOARD_CATEGORY" ADD CONSTRAINT "PK_BOARD_CATEGORY" PRIMARY KEY (
	"CATEGORY_NO"
);

ALTER TABLE "ATTACHMENT" ADD CONSTRAINT "PK_ATTACHMENT" PRIMARY KEY (
	"FILE_NO"
);

ALTER TABLE "MZYM_ADVICE" ADD CONSTRAINT "PK_MZYM_ADVICE" PRIMARY KEY (
	"ADVICE_NO"
);

ALTER TABLE "REPORT_CATEGORY" ADD CONSTRAINT "PK_REPORT_CATEGORY" PRIMARY KEY (
	"CATEGORY_NO"
);

ALTER TABLE "MZYM_BOARD" ADD CONSTRAINT "PK_MZYM_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "MZYM_SERVICE" ADD CONSTRAINT "PK_MZYM_SERVICE" PRIMARY KEY (
	"SERVICE_NO"
);

ALTER TABLE "BOARD_COMMENT" ADD CONSTRAINT "PK_BOARD_COMMENT" PRIMARY KEY (
	"COMMENT_NO"
);

ALTER TABLE "PRODUCT" ADD CONSTRAINT "PK_PRODUCT" PRIMARY KEY (
	"PRODUCT_NO"
);

ALTER TABLE "MZYM_VIDEO" ADD CONSTRAINT "PK_MZYM_VIDEO" PRIMARY KEY (
	"VIDEO_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "PK_REPORT" PRIMARY KEY (
	"REPORT_NO"
);

ALTER TABLE "MZYM_CALENDAR" ADD CONSTRAINT "PK_MZYM_CALENDAR" PRIMARY KEY (
	"CAL_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "PK_PAYMENT" PRIMARY KEY (
	"PAYMENT_NO"
);

ALTER TABLE "FOOD" ADD CONSTRAINT "PK_FOOD" PRIMARY KEY (
	"FOOD_NO"
);

ALTER TABLE "INBODY" ADD CONSTRAINT "PK_INBODY" PRIMARY KEY (
	"USER_NO"
);

ALTER TABLE "SERVICE_CATEGORY" ADD CONSTRAINT "PK_SERVICE_CATEGORY" PRIMARY KEY (
	"CATEGORY_NO"
);

ALTER TABLE "ADVICE_CATEGORY" ADD CONSTRAINT "PK_ADVICE_CATEGORY" PRIMARY KEY (
	"CATEGORY_NO"
);

ALTER TABLE "MZYM_NOTICE" ADD CONSTRAINT "FK_MZYM_MEMBER_TO_MZYM_NOTICE_1" FOREIGN KEY (
	"NOTICE_WRITER"
)
REFERENCES "MZYM_MEMBER" (
	"USER_NO"
);

ALTER TABLE "MZYM_ADVICE" ADD CONSTRAINT "FK_ADVICE_CATEGORY_TO_MZYM_ADVICE_1" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "ADVICE_CATEGORY" (
	"CATEGORY_NO"
);

ALTER TABLE "MZYM_ADVICE" ADD CONSTRAINT "FK_MZYM_MEMBER_TO_MZYM_ADVICE_1" FOREIGN KEY (
	"ADVICE_TR"
)
REFERENCES "MZYM_MEMBER" (
	"USER_NO"
);

ALTER TABLE "MZYM_BOARD" ADD CONSTRAINT "FK_MZYM_MEMBER_TO_MZYM_BOARD_1" FOREIGN KEY (
	"BOARD_WRITER"
)
REFERENCES "MZYM_MEMBER" (
	"USER_NO"
);

ALTER TABLE "MZYM_BOARD" ADD CONSTRAINT "FK_BOARD_CATEGORY_TO_MZYM_BOARD_1" FOREIGN KEY (
	"BORAD_TYPE"
)
REFERENCES "BOARD_CATEGORY" (
	"CATEGORY_NO"
);

ALTER TABLE "MZYM_SERVICE" ADD CONSTRAINT "FK_MZYM_MEMBER_TO_MZYM_SERVICE_1" FOREIGN KEY (
	"SERVICE_USER"
)
REFERENCES "MZYM_MEMBER" (
	"USER_NO"
);

ALTER TABLE "MZYM_SERVICE" ADD CONSTRAINT "FK_SERVICE_CATEGORY_TO_MZYM_SERVICE_1" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "SERVICE_CATEGORY" (
	"CATEGORY_NO"
);

ALTER TABLE "BOARD_COMMENT" ADD CONSTRAINT "FK_MZYM_BOARD_TO_BOARD_COMMENT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "MZYM_BOARD" (
	"BOARD_NO"
);

ALTER TABLE "BOARD_COMMENT" ADD CONSTRAINT "FK_MZYM_MEMBER_TO_BOARD_COMMENT_1" FOREIGN KEY (
	"COMMENT_WRITER"
)
REFERENCES "MZYM_MEMBER" (
	"USER_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MZYM_BOARD_TO_REPORT_1" FOREIGN KEY (
	"BOARD_NO"
)
REFERENCES "MZYM_BOARD" (
	"BOARD_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_BOARD_COMMENT_TO_REPORT_1" FOREIGN KEY (
	"COMMENT_NO"
)
REFERENCES "BOARD_COMMENT" (
	"COMMENT_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_REPORT_CATEGORY_TO_REPORT_1" FOREIGN KEY (
	"CATEGORY_NO"
)
REFERENCES "REPORT_CATEGORY" (
	"CATEGORY_NO"
);

ALTER TABLE "REPORT" ADD CONSTRAINT "FK_MZYM_MEMBER_TO_REPORT_1" FOREIGN KEY (
	"REPORT_USER"
)
REFERENCES "MZYM_MEMBER" (
	"USER_NO"
);

ALTER TABLE "MZYM_CALENDAR" ADD CONSTRAINT "FK_MZYM_MEMBER_TO_MZYM_CALENDAR_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MZYM_MEMBER" (
	"USER_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_PRODUCT_TO_PAYMENT_1" FOREIGN KEY (
	"PRODUCT_NO"
)
REFERENCES "PRODUCT" (
	"PRODUCT_NO"
);

ALTER TABLE "PAYMENT" ADD CONSTRAINT "FK_MZYM_MEMBER_TO_PAYMENT_1" FOREIGN KEY (
	"PAYMENT_USER"
)
REFERENCES "MZYM_MEMBER" (
	"USER_NO"
);

ALTER TABLE "FOOD" ADD CONSTRAINT "FK_MZYM_MEMBER_TO_FOOD_1" FOREIGN KEY (
	"FOOD_USER"
)
REFERENCES "MZYM_MEMBER" (
	"USER_NO"
);

ALTER TABLE "INBODY" ADD CONSTRAINT "FK_MZYM_MEMBER_TO_INBODY_1" FOREIGN KEY (
	"USER_NO"
)
REFERENCES "MZYM_MEMBER" (
	"USER_NO"
);

